stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/ObesityDataSet_raw_and_data_sinthetic.csv
    outs:
      - data/obesity_preprocessed.csv