apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
        - name: reddit-app
          image: us-west1-docker.pkg.dev/mlops9-458317/reddit-app/reddit-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8000